import "./globals.css";
import AOSInitializer from "@/app/components/AOSInitializer";
import { Inria_Sans } from 'next/font/google'

const inriaSans = Inria_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-inria',
})

export const metadata = {
  title: "Portfolio | Daniel Freeman",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inriaSans.className}>
        <AOSInitializer />
        {children}
      </body>
    </html>
  );
}
